# Generated by Django 5.2 on 2025-05-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_todo_deadline_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Praca'), ('home', 'Dom'), ('study', 'Nauka'), ('other', 'Inne')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
