# Generated by Django 5.2 on 2025-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_todo_attachment_todo_category_todo_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
