# Generated by Django 5.2 on 2025-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_todo_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
