# Generated by Django 5.1.9 on 2025-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_voivodeship_usersubmission_city_voivodeship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
